version: '3.9'

services:
  api:
    build: .
    ports: ["8000:8000"]
    volumes:
      - ./app/:/app
      - ./service_lib/:/service_lib
    env_file:
      - ${ENV_FILE_PATH:-.env}

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok/ngrok.yml
  #   ports:
  #     - 4040:4040  # ngrok web UI
  #   depends_on:
  #     - api
  #   network_mode: host  # Important: to access localhost:8000

volumes:
  pgdata: